#! /usr/bin/env bash

set -e -u -o pipefail

default_job_count=4

if [ -n "${JOBS:-}" ]
then
	echo "${JOBS}"
	exit
elif command -v 'nproc' >/dev/null
then
	nproc
else
	case "$(uname -s)" in
		'Linux')
			grep -E "^processor" /proc/cpuinfo | wc -l
			;;
		'FreeBSD')
			sysctl -n hw.ncpu
			;;
		'Darwin')
			sysctl -n hw.logicalcpu || sysctl -n hw.ncpu
			;;
		'MSYS_NT-'*|'CYGWIN_NT-'*|'MINGW'*'_NT-'*)
			if command -v 'wmic' >/dev/null
			then
				wmic cpu get NumberOfLogicalProcessors/Format:List | grep -m1 '=' | cut -f2 -d'='
			else
				echo "${NUMBER_OF_PROCESSORS:-${default_job_count}}"
			fi
			;;
		*)
			echo "${default_job_count}"
			;;
	esac
fi
